/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2024-03-01 03:37:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Instituto Colegiales</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/styleIndex.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <header>\n");
      out.write("    <a href=\"#inicio\"><img src=\"img/escudo.png\" alt=\"logoEscudo\"></a>\n");
      out.write("  </header>\n");
      out.write(" \n");
      out.write("  <nav>\n");
      out.write("    <ul>\n");
      out.write("      <li><a href=\"#oferta-educativa\">Oferta Educativa</a>\n");
      out.write("        <ul>\n");
      out.write("            <li><a href=\"#\">Bachiller</a></li>\n");
      out.write("            <li><a href=\"#\">Cursos ExtraEscolares</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </li>\n");
      out.write("      <li><a href=\"#recursos\">Recursos</a>\n");
      out.write("        <ul>\n");
      out.write("          <li><a href=\"#\">Ambientales</a></li>\n");
      out.write("          <li><a href=\"#\">Didacticos</a></li> \n");
      out.write("        </ul>\n");
      out.write("      </li>\n");
      out.write("      <li><a href=\"#inicio\">Inicio</a>\n");
      out.write("        <ul>\n");
      out.write("          <li><a href=\"#\">Sobre Nosotros</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </li>\n");
      out.write("      <li><a href=\"#contacto\">Ubicacion y Contacto</a></li>\n");
      out.write("      <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login?\">Login</a></li> <!-- redirrecion servlet login -->\n");
      out.write("    </ul>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <div id=\"imgcostado\">\n");
      out.write("    <img src=\"img/imgcostado.png\" alt=\"costado\">\n");
      out.write("  </div>\n");
      out.write("  <main>\n");
      out.write("      <div id=\"jumbotron\">\n");
      out.write("        <img src=\"img/formacion.webp\" alt=\"formacion\">\n");
      out.write("      </div>\n");
      out.write("  </main>\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <section>\n");
      out.write("    <div id=\"mision\"> \n");
      out.write("      <div id=\"grid-1\">\n");
      out.write("        <h2>Nuestra Misión</h2>\n");
      out.write("        <p>Somos una institución privada y laica. </p>\n");
      out.write("        <p>Nos proponemos afianzar la educación en un proceso permanente y transformador a través del cual se vayan desarrollando las potencialidades del hombre como persona individual, socialmente integrada a la comunidad y esencialmente trascendente.</p>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <p>A fines de alcanzar estas metas, el nuevo rol de la escuela en su relación con la comunidad educativa, cuenta con Directivos, Docentes, Familia y Estudiantes que se comprometen con las funciones propias de una educación transformadora, sobre la base de la solidaridad, el cooperativismo, la producción creativa y la coherencia, conduciendo la construcción de conocimientos escolares y científicos con metodologías y técnicas de estudio variadas, que estimulen la formación integral de los niños. Solamente así se logra el ideal de persona y de educación planteados que dan sentido a nuestra identidad como Institución.</p>  \n");
      out.write("      </div>    \n");
      out.write("      <div id=\"grid-2\">\n");
      out.write("        <div id=\"cuadradito\">\n");
      out.write("          <img src=\"img/imgizq.png\" alt=\"cuadrito\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <footer>\n");
      out.write("    <div class=\"footer-container\">\n");
      out.write("      <div class=\"footer-left\">\n");
      out.write("        <h3>Nombre de la Institución</h3>\n");
      out.write("        <p>Dirección de la Institución</p>\n");
      out.write("        <p>Teléfono: 123-456-7890</p>\n");
      out.write("        <p>Email: info@institucion.com</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"footer-right\">\n");
      out.write("        <a><img src=\"img/escudo.png\" alt=\"logoEscudo\"></a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"footer-bottom\">\n");
      out.write("      <b>&copy; Copyright 2023 Colegio Colegiales. Todos los derechos reservados.</b>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
